version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testing
    volumes:
      - ./postgres_db:/usr/src/postgres